# Generated by Django 3.2.13 on 2023-09-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='J_favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Dev', models.CharField(max_length=50)),
                ('Likes', models.CharField(max_length=50)),
                ('Dislikes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='J_recomendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Dev', models.CharField(max_length=50)),
                ('Likes', models.CharField(max_length=50)),
                ('Dislikes', models.CharField(max_length=50)),
            ],
        ),
    ]
